# Generated by Django 5.2.8 on 2025-11-17 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendamento",
            options={
                "ordering": ["data", "hora_inicio"],
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="sala",
            options={"verbose_name": "Sala", "verbose_name_plural": "Salas"},
        ),
        migrations.AddField(
            model_name="agendamento",
            name="data_criacao",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de criação"
            ),
        ),
        migrations.AddField(
            model_name="sala",
            name="ativa",
            field=models.BooleanField(default=True, verbose_name="Sala ativa"),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="data",
            field=models.DateField(verbose_name="Data do agendamento"),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="descricao",
            field=models.TextField(default="", verbose_name="Descrição do agendamento"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="hora_fim",
            field=models.TimeField(verbose_name="Hora de término"),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="hora_inicio",
            field=models.TimeField(verbose_name="Hora de início"),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="agendamento.sala",
                verbose_name="Sala",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="sala",
            name="capacidade",
            field=models.PositiveIntegerField(verbose_name="Capacidade"),
        ),
        migrations.AlterField(
            model_name="sala",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="sala",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome da Sala"),
        ),
    ]
