# Generated by Django 5.2.8 on 2025-11-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0002_alter_agendamento_options_alter_sala_options_and_more"),
    ]

    operations = []
