# Generated by Django 5.2.8 on 2025-11-17 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0003_auto_20251117_1640"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendamento",
            options={
                "ordering": ["data_inicio", "hora_inicio"],
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
            },
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="data",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="data_fim",
            field=models.DateField(
                default=datetime.date(2025, 11, 17),
                verbose_name="Data final do agendamento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agendamento",
            name="data_inicio",
            field=models.DateField(
                default=datetime.date(2025, 11, 17),
                verbose_name="Data inicial do agendamento",
            ),
            preserve_default=False,
        ),
    ]
